# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.network "forwarded_port", guest: 80, host: 8081 # webserver
  config.vm.network "private_network", type: "dhcp" # use this to access seafile
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  vagrant_ansible_remote = ENV['VAGRANT_ANSIBLE_REMOTE']
  if vagrant_ansible_remote
    require_relative "#{vagrant_ansible_remote}/vagrant/provision.rb"
    VagrantAnsibleRemote.provision
  end
end
